name: "tasty-discover"
version: "1.1.0"
synopsis: "Test discovery for the tasty framework."
description: "Test discovery for the tasty framework."
category: "Testing"
author: "Luke Murphy <lukewm@riseup.net>"
maintainer: "Luke Murphy <lukewm@riseup.net>"
copyright: "(c) 2016 Luke Murphy"
license: "MIT"
license-file: "LICENSE.md"
homepage: "https://github.com/lwm/tasty-discover/"
git: "git://github.com/lwm/tasty-discover.git"
bug-reports: "https://github.com/lwm/tasty-discover/issues"
stability: "Experimental"
extra-source-files:
- "test/integration-test/test-configurable-module/*.hs"
- "test/integration-test/test-configurable-module/Nested/*.hs"
- "test/integration-test/test-no-module-suffix/*.hs"
- "test/integration-test/test-no-module-suffix/Nested/*.hs"
- "example/test/*.hs"
- "example/test/AllTheFolders/*.hs"
- "example/test/Thing/AnotherThing/*.hs"
- "test/unit-test/tmpdir/*.hs"
- "test/unit-test/tmpdir/*.md"
dependencies:
- "base ==4.*"
library:
  source-dirs: "src"
  ghc-options: "-Wall"
  exposed-modules:
  - "Test.Tasty.Discover"
  dependencies:
  - "filepath"
  - "directory"
  - "tasty"
  - "tasty-th"
  - "tasty-hunit"
  - "tasty-quickcheck"
  - "tasty-hspec"
executables:
  tasty-discover:
    main: "Main.hs"
    source-dirs: "src"
    ghc-options: "-Wall"
    dependencies:
    - "filepath"
    - "directory"
    - "tasty-discover"
    - "tasty-th"
tests:
  unit-tests:
    main: "Tasty.hs"
    source-dirs: "test/unit-test"
    dependencies:
    - "tasty-discover"
