name: "example"
version: "0.0.1"
synopsis: "Example project for tasty-discover"
description: "Example project for tasty-discover"
license: "MIT"
license-file: "LICENSE.md"

tests:
  example-test:
    main: "Tasty.hs"
    source-dirs: "test"
    dependencies:
    - "base"
    - "tasty-discover"
    - "tasty"
    - "tasty-hspec"
    - "tasty-quickcheck"
    - "tasty-hunit"
